EddyHomePageSolution/EddyNewHome/Controllers/BoardController.cs
using EddyNewHome.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace EddyNewHome.Controllers
{
    public class BoardController : Controller
    {
        EddyNewHomeEntities db = new EddyNewHomeEntities();
        // GET: Board
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            BoardArticles article = new BoardArticles();
            return View(article);
        }

        [HttpPost]
        public ActionResult Create(BoardArticles article)
        {
            article.Email = "test@test.com";
            article.BoardIDX = 2000; //1000: 공지사항 게시판 2000: 자유게시판 3000: QnA
            //article.RegistMemberID = "System";
            article.UserName = "임시사용자";
            article.IPAddress = Commons.GetIpAddress();
            article.ViewCnt = 0;
            article.RegistDate = DateTime.Now;
            article.RegistUserName = "SYSTEM";

            try
            {
                db.BoardArticles.Add(article);
                db.SaveChanges();

                ViewBag.Result = "OK";
            }
            catch (Exception)
            {
                ViewBag.Result = "FAIL";
            }
            return View(article);

           
        }
        [HttpGet]
        public ActionResult List()
        {
            IEnumerable<BoardArticles> list = db.BoardArticles.ToList();
            return View(list);
        }
    }
}

EddyHomePageSolution/EddyNewHome/Views/Board/Create.cshtml
@model EddyNewHome.Models.BoardArticles

@{
    ViewBag.Title = "Create";
}

@section scripts {
    <script>
        $(document).ready(function () {
            var result = "@ViewBag.Result";
            if (result == "OK") {
                alert("정상적으로 저장되었습니다");
            }
            if (result == "FAIL") {
                alert("저장에 실패했습니다");
            }
        });

        function fnSaveCheck() {
            if ($("#ArticleType").val() == "") {
                alert("분류를 선택하세요");
                $("#ArticleType").focus();
                return false;
            }
            if ($("#Title").val() == "") {
                alert("제목을 입력하세요");
                $("#Title").focus();
                return false;
            }
            if ($("#Contents").val() == "") {
                alert("내용을 입력하세요");
                $("#Contents").focus();
                return false;
            }
            return true;
        }
    </script>
}

<div id="feedback" class="inner-content">

    <section id="page-title" class="inner-section">
        <div class="container-fluid nopadding wow fadeInRight" data-wow-delay="0.4s" data-wow-offset="10">
            <h2 class="font-accident-two-normal uppercase">Board</h2>
            <h5 class="font-accident-one-bold hovercolor uppercase">If you need anything else to us, write this ...</h5>
            <p class="small fontcolor-medium">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id metus purus. Ut vulputate, est vel tincidunt mattis, orci neque iaculis lectus, et interdum quam felis vel tortor. Fusce ultrices dui quis nunc dignissim faucibus. Ut ac odio quis nibh viverra fringilla ac id nisi. Suspendisse tincidunt augue quis ligula cursus, non efficitur ligula faucibus. Mauris id neque maximus, tincidunt metus et, sodales nulla.
            </p>
        </div>
    </section>

    <!-- Board Block -->
    <section class="inner-section feedback feedback-light">

        <div class="container-fluid nopadding">

            <div class="row">

                <div class="col-md-2">&nbsp;</div>
                <div class="col-md-8 e-centered wow fadeInDown" data-wow-delay="0.6s" data-wow-offset="10">
                    <div class="dividewhite2"></div>
                    <div id="form-messages"></div>
                    <form method="post" action="@Url.Action("Create","Board")" class="wpcf7-form">
                        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
                        <div class="field">
                            @*@Html.TextBoxFor(m => m.ArticleType, new { PlaceHolder = "게시글 유형을 입력하세요." })*@
                            @Html.DropDownListFor(m => m.ArticleType, new SelectList(new List<object>
    {
    new {value = "", text = "유형을 선택하세요" },
    new {value = "1", text = "C#" },
    new {value = "2", text = "JAVA" },
    new {value = "3", text = "C++" }
    }, "value", "text", Model.ArticleType), new { style = "padding: 12px 15px; margin-bottom:10px; width:100%; border:solid 1px #FF0000;" })
                        </div>
                        <div class="field">
                            @Html.TextBoxFor(m => m.Title, new { PlaceHolder = "제목을 입력하세요." })
                        </div>

                        <div class="field">
                            @Html.TextAreaFor(m => m.Contents, new { PlaceHolder = "내용을 입력하세요," })
                        </div>

                        <div class="dividewhite2"></div>

                        <div class="field text-center">
                            <button type="submit" class="btn btn-lg btn-lgr-str" onclick="return fnSaveCheck();">Save</button>
                            <a href="/Board/List" class="btn btn-lg btn-lgr-str">List</a>
                        </div>
                    </form>
                </div>
                <div class="col-md-2">&nbsp;</div>
                <div class="col-md-12 divider-dynamic"></div>
            </div>

        </div>

        <div class="dividewhite6"></div>

    </section>
    <!-- /Feedback Block -->

</div>

EddyHomePageSolution/EddyNewHome/Views/Board/List.cshtml
@model IEnumerable<EddyNewHome.Models.BoardArticles>

@{
    ViewBag.Title = "List";
}

@section scripts {
    <script>
        $(document).ready(function () {
            $(".footable").footable();
        });
    </script>
}

<div id="feedback" class="inner-content">
    <section id="page-title" class="inner-section">
        <div class="container-fluid nopadding wow fadeInRight" data-wow-delay="0.4s" data-wow-offset="10">
            <h2 class="font-accident-two-normal uppercase">Board List</h2>
            <h5 class="font-accident-one-bold hovercolor uppercase">
                @Html.ActionLink("글쓰기", "Create")
            </h5>
            <p class="small fontcolor-medium">
            </p>
        </div>
    </section>

    <!-- List Block -->
    <section class="inner-section feedback feedback-light">
        <div class="container-fluid nopadding">
            <div class="row">
                <div class="col-md-12 e-centered wow fadeInDown" data-wow-delay="0.6s" data-wow-offset="10">
                    <div class="dividewhite2"></div>
                    <div id="form-messages"></div>
                    <!--실제 리스트 영역 시작-->
                    <table class="footable table table-striped toggle-arrow-tiny" data-page-size="10">
                        <thead>
                            <tr>
                                <th data-sort-ignore="true">
                                    @Html.DisplayNameFor(model => model.ArticleIDX)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ArticleType)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Title)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Email)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.IPAddress)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.RegistDate)
                                </th>

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.ArticleIDX)</td>
                                <td>@Html.DisplayFor(modelItem => item.ArticleType)</td>
                                <td>@Html.DisplayFor(modelItem => item.Title)</td>
                                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                                <td>@Html.DisplayFor(modelItem => item.IPAddress)</td>
                                <td>@Html.DisplayFor(modelItem => item.RegistDate)</td>
                            </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="6" style="text-align:right">
                                    <ul class="pagination pull-right"></ul>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                    <!--실제 리스트 영역 끝-->
                </div>
                <div class="col-md-12 divider-dynamic"></div>
            </div>

        </div>

        <div class="dividewhite6"></div>

    </section>
</div>

@*<div id="blogpost" class="inner-content">
        <section class="inner-content">
            <div class="container-fluid nopadding">
                <div class="wow fadeInDown" data-wow-delay="0.2s" data-wow-offset="10">
                    <div id="post-comment">
                        <h4 class="font-accident-one-bold">회원목록</h4>
                        <p>
                            @Html.ActionLink("Register", "Entry")
                        </p>
                    </div>
                </div>
            </div>
        </section>
    </div>*@