EddyHomePageSolution/EddyNewHome/Models/Members.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddyNewHome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Members()
        {
            this.ArticleComments = new HashSet<ArticleComments>();
            this.BoardArticles = new HashSet<BoardArticles>();
        }
    
        public string MemberID { get; set; }
        public string MemberPWD { get; set; }
        public string MemberName { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Levels { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleComments> ArticleComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoardArticles> BoardArticles { get; set; }
    }
}

EddyHomePageSolution/EddyNewHome/Controllers/MemberController.cs
using EddyNewHome.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EddyNewHome.Controllers
{
    public class MemberController : Controller
    {
        EddyNewHomeEntities db = new EddyNewHomeEntities();
        // GET: Member
        public ActionResult Entry()
        {
            Members member = new Members();
            return View(member);
        }

        [HttpPost]
        public ActionResult Entry(Members member)
        {
            member.EntryDate = DateTime.Now;
            try
            {
                db.Members.Add(member);
                db.SaveChanges();     //트렌젝션 커밋
                ViewBag.Result = "OK";
            }
            catch (Exception ex)
            {
                ViewBag.Result = "FAIL";
                //ViewBag.Result = $"{ex.Message}";
            }

            return View(member);
        }

        [HttpGet]
        public ActionResult List()
        {
            IEnumerable<Members> list = db.Members.ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult Edit(string memberid)
        {
            Members member = db.Members.Where(m => m.MemberID == memberid).FirstOrDefault();
            return View(member);
        }

        [HttpPost]
        public ActionResult Edit(Members member)
        {
            //Members dbMember = db.Members.Where(m => m.MemberID == member.MemberID).FirstOrDefault();
            Members origin = db.Members.Find(member.MemberID);
            try
            {
                origin.MemberName = member.MemberName;
                origin.MemberPWD = member.MemberPWD;
                origin.Email = member.Email;
                origin.Telephone = member.Telephone;

                db.Entry(origin).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                ViewBag.Result = "OK";
            }
            catch (Exception)
            {
                ViewBag.Result = "FAIL";
            }
            return View(origin);
        }

        [HttpGet]
        public ActionResult Delete(string memberid)
        {
            Members member = db.Members.Find(memberid);
            db.Members.Remove(member);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        /// <summary>
        /// Ajax 중복체크 메서드
        /// </summary>
        /// <param name="memberid"></param>
        /// <returns></returns>

        [HttpGet]
        public JsonResult IDCheck(string memberid)
        {
            string result = string.Empty;
            Members member = db.Members.Find(memberid);
            if (member == null)
                result = "OK";
            else
                result = "FAIL";
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

EddyHomePageSolution/EddyNewHome/Views/Member/Edit.cshtml
@using EddyNewHome.Models;
@model EddyNewHome.Models.Members

@{
    ViewBag.Title = "Edit";
}

@section scripts {
    <script>
    $(document).ready(function () {
        var result = "@ViewBag.Result";
        if (result == "OK") {
            alert("정상적으로 저장되었습니다.");
        }
        else if (result == "FAIL" ) {
            alert("저장 실패");
        }
    });

    function fnDeleteConfirm() {
        if (confirm("삭제하시겠습니까?") == true) {
            location.href = "/Member/Delete?memberid=" + $("#MemberID").val();
        } else {
            return false;
        }
    }

    function fnSaveCheck() {
        if ($("#MemberID").val() == "") {
            alert("아이디를 입력해주세요");
            $("#MemberID").focus();
            return false;
        }

        if ($("#MemberName").val() == "") {
            alert("이름을 입력해주세요");
            $("#MemberName").focus();
            return false;
        }

        if ($("#MemberPWD").val() == "") {
            alert("암호를 입력해주세요");
            $("#MemberPWD").focus();
            return false;
        }
        return true;
    }
    </script>
}


<div id="feedback" class="inner-content">
    <section id="page-title" class="inner-section">
        <div class="container-fluid nopadding wow fadeInRight" data-wow-delay="0.4s" data-wow-offset="10">
            <h2 class="font-accident-two-normal uppercase">Edit</h2>
            <h5 class="font-accident-one-bold hovercolor uppercase">Hard-working person on the way to the success...</h5>
            <p class="small fontcolor-medium">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id metus purus. Ut vulputate, est vel tincidunt mattis, orci neque iaculis lectus, et interdum quam felis vel tortor. Fusce ultrices dui quis nunc dignissim faucibus. Ut ac odio quis nibh viverra fringilla ac id nisi. Suspendisse tincidunt augue quis ligula cursus, non efficitur ligula faucibus. Mauris id neque maximus, tincidunt metus et, sodales nulla.
            </p>
        </div>
    </section>

    <!-- Feedback Block -->
    <section class="inner-section feedback feedback-light">

        <div class="container-fluid nopadding">

            <div class="row">

                <div class="col-md-2">&nbsp;</div>
                <div class="col-md-8 e-centered wow fadeInDown" data-wow-delay="0.6s" data-wow-offset="10">
                    <div class="dividewhite2"></div>
                    <div id="form-messages"></div>
                    <form method="post" action="@Url.Action("Edit","Member")" class="wpcf7-form">
                        <div class="field">
                            @Html.TextBoxFor(m => m.MemberID, new { placeHolder = "아이디를 입력하세요" })
                        </div>
                        <div class="field">
                            @Html.TextBoxFor(m => m.MemberName, new { placeHolder = "이름을 입력하세요" })
                        </div>

                        <div class="field">
                            @Html.PasswordFor(m => m.MemberPWD, new { placeHolder = "암호를 입력하세요" })
                        </div>

                        <div class="field">
                            @Html.TextBoxFor(m => m.Email, new { placeHolder = "메일을 입력하세요" })
                        </div>

                        <div class="field">
                            @Html.TextBoxFor(m => m.Telephone, new { placeHolder = "폰번호를 입력하세요" })
                        </div>
                        <div class="dividewhite2"></div>
                        <div class="field text-center">
                            <button id="btnSave" type="submit" class="btn btn-lg btn-lgr-str" onclick="return fnSaveCheck();">Update</button>
                            <button type="button" class="btn btn-lg btn-lgr-str" onclick="return fnDeleteConfirm();">Delete</button>
                            <a href="/Member/List" class="btn btn-lg btn-lgr-str">List</a>
                        </div>
                    </form>
                </div>
                <div class="col-md-2">&nbsp;</div>
                <div class="col-md-12 divider-dynamic"></div>
            </div>
        </div>
        <div class="dividewhite6"></div>
    </section>
</div>

EddyHomePageSolution/EddyNewHome/Views/Member/Entry.cshtml
@using EddyNewHome.Models;
@model EddyNewHome.Models.Members
 
@{
    ViewBag.Title = "Entry";
}

@section scripts {
<script>
    $(document).ready(function () {
        var result = "@ViewBag.Result";
        if (result == "OK") {
            alert("정상적으로 저장되었습니다.");
        }
        else if (result == "FAIL" ) {
            alert("저장 실패");
        }
    });

    //아이디 중복체크
    function fnDoubleCheck() {
        if ($("#MemberID").val() == "") {
            alert("아이디를 입력해주세요");
            $("#MemberID").focus();
            return false;
        }

        $.ajax({
            type: "GET",
            contentType: "application/json; charset=utf-8",
            url: "/Member/IDCheck?memberid=" + $("#MemberID").val(),
            data: "{}",
            dataType: "Json"
        }).done(function (response) {
                //debuger;
                if (response == "OK") {
                    alert("사용 가능한 아이디입니다.");
                    $("#btnSave").removeAttr("disable");
                }
                else {
                    alert("중복 아이디가 존재합니다.");
                    $("#MemberID").val("");
                    $("#MemberID").focus();
                    $("#MemberID").attr("disable", true);
                }
        }).fail(function (data) {
            if (data.responseText != "") {
                alert(data.responseText);
            }
            else {
                alert("에러가 발생했습니다.");
            }
        });
    }

    function fnSaveCheck() {
        if ($("#MemberID").val() == "") {
            alert("아이디를 입력해주세요");
            $("#MemberID").focus();
            return false;
        }

        if ($("#MemberName").val() == "") {
            alert("이름을 입력해주세요");
            $("#MemberName").focus();
            return false;
        }

        if ($("#MemberPWD").val() == "") {
            alert("암호를 입력해주세요");
            $("#MemberPWD").focus();
            return false;
        }
        return true;
    }
</script>
}


    <div id="feedback" class="inner-content">
        <section id="page-title" class="inner-section">
            <div class="container-fluid nopadding wow fadeInRight" data-wow-delay="0.4s" data-wow-offset="10">
                <h2 class="font-accident-two-normal uppercase">Register</h2>
                <h5 class="font-accident-one-bold hovercolor uppercase">Hard-working person on the way to the success...</h5>
                <p class="small fontcolor-medium">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id metus purus. Ut vulputate, est vel tincidunt mattis, orci neque iaculis lectus, et interdum quam felis vel tortor. Fusce ultrices dui quis nunc dignissim faucibus. Ut ac odio quis nibh viverra fringilla ac id nisi. Suspendisse tincidunt augue quis ligula cursus, non efficitur ligula faucibus. Mauris id neque maximus, tincidunt metus et, sodales nulla.
                </p>
            </div>
        </section>

        <!-- Feedback Block -->
        <section class="inner-section feedback feedback-light">

            <div class="container-fluid nopadding">

                <div class="row">

                    <div class="col-md-2">&nbsp;</div>
                    <div class="col-md-8 e-centered wow fadeInDown" data-wow-delay="0.6s" data-wow-offset="10">
                        <div class="dividewhite2"></div>
                        <div id="form-messages"></div>
                        <form method="post" action="@Url.Action("Entry","Member")" class="wpcf7-form">
                            <div class="row">
                                <div class="col-md-10">
                                    <div class="field">
                                        @Html.TextBoxFor(m => m.MemberID, new { placeHolder = "아이디를 입력하세요" })
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <button type="button" class="btn btn-lg btn-lgr-str" onclick="fnDoubleCheck()">중복 검사</button>
                                </div>
                            </div>

                            <div class="field">
                                @Html.TextBoxFor(m => m.MemberName, new { placeHolder = "이름을 입력하세요" })
                            </div>

                            <div class="field">
                                @Html.PasswordFor(m => m.MemberPWD, new { placeHolder = "암호를 입력하세요" })
                            </div>

                            <div class="field">
                                @Html.TextBoxFor(m => m.Email, new { placeHolder = "메일을 입력하세요" })
                            </div>

                            <div class="field">
                                @Html.TextBoxFor(m => m.Telephone, new { placeHolder = "폰번호를 입력하세요" })
                            </div>

                            <div class="dividewhite2"></div>

                            <div class="field text-center">
                                <button id="btnSave" type="submit" class="btn btn-lg btn-lgr-str" onclick="return fnSaveCheck();">Save</button>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-2">&nbsp;</div>
                    <div class="col-md-12 divider-dynamic"></div>
                </div>

            </div>

            <div class="dividewhite6"></div>

        </section>
        <!-- /Feedback Block -->
    </div>

EddyHomePageSolution/EddyNewHome/Views/Member/List.cshtml
@model IEnumerable<EddyNewHome.Models.Members>

@{
    ViewBag.Title = "List";
}

@section scripts {
    <script>
        $(document).ready(function () {
            $(".footable").footable();
        });
    </script>
}

<div id="feedback" class="inner-content">
    <section id="page-title" class="inner-section">
        <div class="container-fluid nopadding wow fadeInRight" data-wow-delay="0.4s" data-wow-offset="10">
            <h2 class="font-accident-two-normal uppercase">Member List</h2>
            <h5 class="font-accident-one-bold hovercolor uppercase">
                @Html.ActionLink("Register", "Entry")
            </h5>
            <p class="small fontcolor-medium">
            </p>
        </div>
    </section>

    <!-- List Block -->
    <section class="inner-section feedback feedback-light">
        <div class="container-fluid nopadding">
            <div class="row">
                <div class="col-md-12 e-centered wow fadeInDown" data-wow-delay="0.6s" data-wow-offset="10">
                    <div class="dividewhite2"></div>
                    <div id="form-messages"></div>
                    <!--실제 리스트 영역 시작-->
                    <table class="footable table table-striped toggle-arrow-tiny" data-page-size="10">
                        <thead>
                            <tr>
                                <th data-sort-ignore="true">NUMBER</th>
                                <th>
                                    @Html.DisplayNameFor(model => model.MemberID)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.MemberName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Email)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Telephone)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.EntryDate)
                                </th>

                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int idx = 1;
                            }

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <th>@idx.ToString()</th>
                                    <td><a href="/Member/Edit?memberid=@item.MemberID">@item.MemberID</a></td>
                                    <td>@Html.DisplayFor(modelItem => item.MemberName)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Email)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Telephone)</td>
                                    <td>@Html.DisplayFor(modelItem => item.EntryDate)</td>
                                </tr>
                                idx++;
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="6" style="text-align:right">
                                    <ul class="pagination pull-right"></ul>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                    <!--실제 리스트 영역 끝-->
                </div>
                <div class="col-md-12 divider-dynamic"></div>
            </div>

        </div>

        <div class="dividewhite6"></div>

    </section>
</div>

@*<div id="blogpost" class="inner-content">
        <section class="inner-content">
            <div class="container-fluid nopadding">
                <div class="wow fadeInDown" data-wow-delay="0.2s" data-wow-offset="10">
                    <div id="post-comment">
                        <h4 class="font-accident-one-bold">회원목록</h4>
                        <p>
                            @Html.ActionLink("Register", "Entry")
                        </p>
                    </div>
                </div>
            </div>
        </section>
    </div>*@